### PR TITLE
Fix devserver on Windows

### LINKED ISSUE #960: Fauxton dev server not running on Windows 7
I cloned the repository, installed dependencies with npm, and changed the host in the setting.json file however I am receiving the following error:

```
$ npm run dev

> fauxton@1.1.13 dev C:\Users\schader1\couchdb-fauxton
> node ./devserver.js

setup dev environment
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn grunt ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

NPM Debug log:

```
10 verbose lifecycle fauxton@1.1.13~dev: CWD: C:\Users\schader1\couchdb-fauxton
11 silly lifecycle fauxton@1.1.13~dev: Args: [ '/d /s /c', 'node ./devserver.js' ]
12 silly lifecycle fauxton@1.1.13~dev: Returned: code: 1  signal: null
13 info lifecycle fauxton@1.1.13~dev: Failed to exec dev script
14 verbose stack Error: fauxton@1.1.13 dev: `node ./devserver.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid fauxton@1.1.13
16 verbose cwd C:\Users\schader1\couchdb-fauxton
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error fauxton@1.1.13 dev: `node ./devserver.js`
22 error Exit status 1
23 error Failed at the fauxton@1.1.13 dev script 'node ./devserver.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the fauxton package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./devserver.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs fauxton
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls fauxton
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### PR DESCRIPTION
**Pull request by popojargo**
## Overview

We were unable to run: `npm run dev` on Windows.

## Testing recommendations

Run `npm run dev` on a non-windows OS and it should still start the devserser.
Run `npm run dev`on a windows OS and it should successfully start the devserver.

## GitHub issue number

Fixes #960 

## Checklist

- [x] Code is written and works correctly;
- [ ] Changes are covered by tests;
- [ ] Documentation reflects the changes;
- [ ] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the correct tag once a new Fauxton release is made

### CODE REVIEW

File: devserver.js [hunk 1]
```diff
@@ -31,8 +31,9 @@ const devSetup = function (cb) {
   if (settings.noClean) {
     cmd = 'devSetup';
   }
-
-  const grunt = spawn('grunt', [cmd]);
+  let isOnWindows = process.platform === 'win32';
```
Comment (garrensmith) [inline devserver.js]: This is great. Could you make both of these `const`

**Comment by garrensmith** [comment]
Awesome. Thanks this is great.
